### ISSUE TITLE
uncaught exceptions in production

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-basket-proxy#16]
There have been a couple of uncaught exceptions, but I don't have any details. See https://github.com/mozilla/mozlog/issues/8

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla/mozlog/issues/8#issuecomment-181114473

**Comment by rfk** [comment]
(putting this back in "next" until we get the fixed version of mozlog deployed and can get some actionable tracebacks)

**Comment by vladikoff** [comment]
waiting for deploy...

**Comment by rfk** [comment]
the train went out, IIUC this is no longer "blocked"

**Comment by jrgm** [comment]
Yeah, not blocked anymore. Thanks for the fix @seanmonstar and @rfk!
